const test=require('node:test');
const assert=require('node:assert/strict');
const {createMcpHandler}=require('../lib/mcp');
function handler(){return createMcpHandler({name:'test',instructions:'Pure arithmetic',tools:[{name:'compute',inputSchema:{type:'object',required:['amount'],properties:{amount:{type:'number',minimum:0},items:{type:'array',items:{type:'object',required:['amount'],properties:{amount:{type:'number',minimum:0}}}}}}}],callTool:(_,a)=>({amount:a.amount})});}
async function request(body){const res={headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(v){this.body=v;return this},end(){return this}};await handler()({method:'POST',body},res);return res;}
test('Reject missing, wrong-type, negative, unknown and nested invalid inputs',async()=>{for(const a of [{},{amount:'100'},{amount:-1},{amount:1,secret:'no'},{amount:1,items:[{amount:-5}]}]){const r=await request({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'compute',arguments:a}});assert.equal(r.body.result.isError,true);assert.equal(r.body.result.structuredContent,undefined)}});
test('Successful calls log only pseudonyms and technical metadata',async()=>{const logs=[];const old=console.log;try{console.log=s=>logs.push(JSON.parse(s));const r=await request({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'compute',arguments:{amount:98765},_meta:{'openai/subject':'private-user','openai/session':'private-session','openai/organization':'private-org','openai/locale':'en-US'}}});assert.equal(r.body.result.structuredContent.amount,98765);assert.equal(logs.length,1);assert.equal(logs[0].event,'money_plugin_tool_call');assert.match(logs[0].subject,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(logs).includes('private-'));assert.ok(!JSON.stringify(logs).includes('98765'));}finally{console.log=old}});
test('Tool metadata describes stateless read-only behavior',async()=>{const r=await request({jsonrpc:'2.0',id:2,method:'tools/list'});assert.deepEqual(r.body.result.tools[0].annotations,{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false});assert.equal(r.body.result.tools[0].inputSchema.additionalProperties,false)});
test('Unknown tool is a protocol error; notifications have no body',async()=>{const r=await request({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'missing'}});assert.equal(r.body.error.code,-32602);const n=await request({jsonrpc:'2.0',method:'notifications/initialized'});assert.equal(n.statusCode,202);assert.equal(n.body,undefined)});
