import json,pathlib
root=pathlib.Path(__file__).resolve().parents[1]
B=dict(eligibility_pass=True,mandatory_covered=19,mandatory_total=20,critical_gaps=0,strategic_fit=90,delivery_fit=90,evidence_readiness=90,estimated_response_hours=24,days_to_deadline=10)
G=dict(eligibility_pass=True,mandatory_covered=9,mandatory_total=10,strategic_fit=90,evidence_readiness=90,cofunding_readiness=90,estimated_application_hours=20,days_to_deadline=14,critical_gaps=0)
R=dict(annualized_spend=12000,days_to_renewal=90,notice_period_days=30,utilization_percent=30,overlap_score=0,criticality=50,auto_renews=True)
S=dict(rate_amount=150,rate_unit='hour',lean_effort=20,expected_effort=30,protected_effort=40,overhead_percent=10)
fixtures={
'scopeguard':[(S,{'lean_price':3300,'expected_price':4950,'protected_price':6600}), (dict(rate_amount=200,rate_unit='hour',lean_effort=15,expected_effort=15,protected_effort=15,minimum_fee=5000),{'expected_price':5000}), (dict(incremental_effort=8,rate_amount=125,rate_unit='hour'),{'incremental_price':1000}), (dict(rate_amount=1000,rate_unit='day',lean_effort=6,expected_effort=8,protected_effort=10),{'expected_price':8000}), (dict(rate_amount=900,rate_unit='day',lean_effort=6,expected_effort=7,protected_effort=8),{'protected_price':7200})],
'bidready':[(B,{'recommendation':'BID'}),(dict(B,eligibility_pass=False),{'recommendation':'NO_BID'}),(dict(B,estimated_response_hours=60,days_to_deadline=3,evidence_readiness=55),{'workload_fit':0}),(dict(B,mandatory_covered=12,mandatory_total=18,evidence_readiness=50),{'compliance_percent':67}),(dict(B,critical_gaps=2,strategic_fit=60,delivery_fit=65,evidence_readiness=60),{'recommendation':'NO_BID'})],
'grantfit':[(G,{'recommendation':'APPLY'}),(dict(G,eligibility_pass=False),{'recommendation':'NO_GO'}),(dict(G,evidence_readiness=35,critical_gaps=2),{'recommendation':'NO_GO'}),(dict(G,cofunding_readiness=20),{'recommendation':'APPLY'}),(dict(G,estimated_application_hours=50,days_to_deadline=4),{'application_capacity':4})],
'refundradar':[(dict(purchase_age_days=10,return_window_days=30),{'route':'STANDARD_RETURN'}),(dict(purchase_age_days=2,auto_renewal_days_ago=2,policy_allows_exception=True),{'route':'AUTO_RENEWAL'}),(dict(purchase_age_days=1,duplicate_charge=True),{'route':'DUPLICATE_CHARGE'}),(dict(purchase_age_days=180,item_defective=True,policy_allows_exception=True),{'route':'DEFECT_OR_WARRANTY'}),(dict(purchase_age_days=14,service_not_delivered=True),{'route':'NON_DELIVERY'})],
'invoicechaser':[(dict(invoice_amount=2000,days_overdue=5,reminders_sent=0),{'stage':'FRIENDLY_REMINDER'}),(dict(currency='EUR',invoice_amount=4500,days_overdue=25,reminders_sent=1),{'stage':'FIRM_REMINDER'}),(dict(invoice_amount=10000,amount_paid=4000,days_overdue=20),{'outstanding_amount':6000}),(dict(invoice_amount=3000,days_overdue=35,promised_payment_date_missed=True),{'stage':'FIRM_PRE_ESCALATION'}),(dict(invoice_amount=3000,days_overdue=50,disputed=True),{'stage':'RESOLVE_DISPUTE'})],
'vendorguard':[(dict(term_months=12,one_time_fee=1000,monthly_fee=500),{'total_cost_of_ownership':7000}),(dict(term_months=24,implementation_fee=15000,monthly_fee=2000),{'total_cost_of_ownership':63000}),(dict(term_months=24,monthly_fee=1000,annual_price_increase_percent=10),{'total_cost_of_ownership':25200}),(dict(term_months=12,monthly_fee=800,estimated_monthly_usage_fee=300,monthly_support_fee=200),{'total_cost_of_ownership':15600}),(dict(term_months=36,monthly_fee=1000,expected_exit_cost=5000),{'total_cost_of_ownership':41000})],
'dealdesk':[(dict(list_price=10000,proposed_price=8000,cost_to_serve=6000,target_margin_percent=30),{'meets_target':False,'gross_margin_percent':25}),(dict(list_price=50000,proposed_price=50000,cost_to_serve=25000,sales_commission_percent=10,target_margin_percent=25),{'gross_margin_percent':40}),(dict(list_price=20000,proposed_price=20000,cost_to_serve=10000,support_cost=3000,target_margin_percent=30),{'gross_margin_percent':35}),(dict(list_price=80000,proposed_price=80000,cost_to_serve=60000,target_margin_percent=25),{'minimum_price_for_target':80000}),(dict(list_price=120000,proposed_price=120000,cost_to_serve=60000,target_margin_percent=30),{'meets_target':True,'gross_margin_percent':50})],
'renewalradar':[(dict(R,days_to_renewal=20),{'action':'NOTICE_WINDOW_AT_RISK','days_until_notice_deadline':-10}),(dict(R,annualized_spend=24000,utilization_percent=25,overlap_score=70,criticality=20),{'estimated_underutilized_spend':18000}),(dict(R,price_increase_percent=20,utilization_percent=95,days_to_renewal=60),{'days_until_notice_deadline':30}),(dict(R,annualized_spend=3000,utilization_percent=100,criticality=100),{'action':'LIKELY_RENEW'}),(dict(R,days_to_renewal=45),{'days_until_notice_deadline':15})],
'cashleak':[(dict(monthly_cost=1000,utilization_percent=10,overlap_score=90,essentiality=10,owner_known=False),{'estimated_underutilized_spend':10800,'action':'CUT_OR_RENEGOTIATE'}),(dict(monthly_cost=2000,utilization_percent=95,overlap_score=0,essentiality=100,owner_known=True),{'action':'KEEP_MONITORED'}),(dict(monthly_cost=1000,price_increase_percent=25,utilization_percent=70,overlap_score=50,essentiality=40,owner_known=True),{'review_priority':40}),(dict(monthly_cost=600,utilization_percent=50,overlap_score=60,essentiality=40,owner_known=False),{'review_priority':44}),(dict(monthly_cost=300,utilization_percent=40,overlap_score=30,essentiality=50,owner_known=True),{'annualized_cost':3600,'estimated_underutilized_spend':2160})],
 'travelclaim':[(dict(arrival_delay_minutes=300),{'disruption_level':'MAJOR','policy_check_required':True}),(dict(canceled=True,rerouted=True),{'disruption_level':'MAJOR'}),(dict(denied_boarding=True),{'disruption_level':'MAJOR'}),(dict(baggage_delay_hours=36),{'disruption_level':'SIGNIFICANT'}),(dict(arrival_delay_minutes=90),{'disruption_level':'MODERATE'})]
}
for name,cases in fixtures.items():
 p=root/'plugins'/name/'plugin.json';d=json.loads(p.read_text());review=d['extensions']['com.openai']['review']; pos=review['test_cases']['positive']
 for i,(args,expected) in enumerate(cases):
  pos[i]['prompt']=pos[i]['prompt'].split('\n\nSynthetic reviewer inputs:')[0]+'\n\nSynthetic reviewer inputs: '+json.dumps(args,sort_keys=True)+'. All unlisted optional monetary costs are confirmed zero for this test; all currencies are USD unless stated. Use these supplied values, keep policy/contract verification separate, and expose assumptions.'
 if name=='scopeguard':
  pos[3]['prompt']+=' Website brief: five static pages, supplied copy, one language, two review rounds, no CMS, no migration. Supplied effort includes discovery, design, development, QA, project management and handoff.'
 if name=='grantfit':pos[3]['expected_behavior']='Quantify co-funding risk; a weighted APPLY score is provisional and cannot override a mandatory unfulfilled co-funding gate. Verify actual secured funds before committing.'
 if name=='cashleak':pos[3]['expected_behavior']='Increase review priority versus the same economics with a known owner. A score of 44 remains KEEP_MONITORED; assign an owner and verify usage.'
 d['extensions']['com.openai']['onboardingSkill']='./skills/'+next((root/'plugins'/name/'skills').iterdir()).name+'/SKILL.md'
 d['extensions']['com.openai']['publication']['release_notes']='Initial public release. Includes typed-input validation, explicit read-only tool annotations, pseudonymous technical telemetry, deterministic review fixtures, and no commerce.'
 p.write_text(json.dumps(d,indent=2)+'\n')
 output=[]
 for i,(args,expected) in enumerate(cases):output.append({'index':i+1,'tool':pos[i]['tools_triggered'],'arguments':args,'expected_fields':expected})
 (root/'review'/f'{name}-fixtures.json').write_text(json.dumps(output,indent=2)+'\n')
